import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
  root:   {flex: 1},

  // Header
  header: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 42 : 50,
    paddingBottom: 12,
    borderBottomWidth: 1, borderBottomColor: '#111827',
  },
  headerTitle: {fontSize: 20, fontWeight: '800', color: '#E8EDF5', letterSpacing: 0.3},
  headerSub:   {fontSize: 10, color: '#3D4E6A', marginTop: 2, letterSpacing: 1.4, textTransform: 'uppercase'},
  syncBtn:        {width: 36, height: 36, borderRadius: 18, backgroundColor: '#111827', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#1E2D45'},
  syncBtnActive:  {borderColor: '#5352ED'},
  syncBtnText:    {color: '#7EB8F7', fontSize: 16, fontWeight: '700'},

  scroll:        {flex: 1},
  scrollContent: {paddingHorizontal: 14, paddingTop: 8},

  // Gauge Card
  gaugeCard: {
    marginVertical: 10,
    backgroundColor: '#080B14',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1A2235',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 10,
  },
  gaugeAccentBar:   {height: 3},
  gaugeCircleWrap:  {alignItems: 'center', paddingTop: 24, paddingBottom: 20},
  gaugeOuterRing: {
    width: 180, height: 180, borderRadius: 90,
    borderWidth: 3,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#060810',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.9,
    shadowRadius: 18,
    elevation: 12,
  },
  gaugeInner:       {alignItems: 'center'},
  gaugeEmoji:       {fontSize: 28, marginBottom: 1},
  gaugeScore:       {fontSize: 54, fontWeight: '900', lineHeight: 58},
  gaugeScoreUnit:   {fontSize: 9, color: '#3D4E6A', letterSpacing: 1.5, textTransform: 'uppercase', marginTop: 1},
  gaugeStatePill: {
    flexDirection: 'row', alignItems: 'center',
    borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3,
    borderWidth: 1, marginTop: 6,
  },
  gaugeStateLabel:  {fontSize: 11, fontWeight: '700', letterSpacing: 0.4},
  // Stats strip
  gaugeStatsStrip: {
    flexDirection: 'row',
    borderTopWidth: 1, borderBottomWidth: 1,
    borderColor: '#111827',
  },
  gaugeStatItem:  {flex: 1, alignItems: 'center', paddingVertical: 12},
  gaugeStatVal:   {fontSize: 14, fontWeight: '800', color: '#E8EDF5'},
  gaugeStatKey:   {fontSize: 8, color: '#3D4E6A', letterSpacing: 1.3, textTransform: 'uppercase', marginTop: 2},
  gaugeStatSep:   {width: 1, backgroundColor: '#111827', marginVertical: 8},
  // Zone bar
  gaugeZoneWrap:       {padding: 14, paddingTop: 12},
  gaugeZoneHeaderRow:  {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9},
  gaugeZoneHeaderLabel:{fontSize: 10, color: '#3D4E6A', letterSpacing: 1.3, textTransform: 'uppercase', fontWeight: '700'},
  gaugeZoneHeaderPct:  {fontSize: 13, fontWeight: '800'},
  gaugeSegBar:         {flexDirection: 'row', gap: 3},
  gaugeSegSlot:        {flex: 1},
  gaugeSegTrack:       {height: 10, borderRadius: 5, overflow: 'hidden'},
  gaugeSegFill:        {height: '100%', borderRadius: 5},
  gaugeTickRow:        {flexDirection: 'row', justifyContent: 'space-between', marginTop: 5},
  gaugeTick:           {fontSize: 8, color: '#3D4E6A', fontWeight: '600'},
  gaugeZoneLegend:     {flexDirection: 'row', justifyContent: 'space-between', marginTop: 9},
  gaugeZoneLegendItem: {flexDirection: 'row', alignItems: 'center', gap: 4},
  gaugeZoneLegendDot:  {width: 6, height: 6, borderRadius: 3},
  gaugeZoneLegendText: {fontSize: 8, color: '#3D4E6A', fontWeight: '600'},

  // SOS Banner
  sosBanner:    {flexDirection: 'row', alignItems: 'center', borderRadius: 10, borderWidth: 1, paddingVertical: 9, paddingHorizontal: 13, marginBottom: 9, backgroundColor: '#FF336608', gap: 7},
  sosBannerIcon:{fontSize: 14},
  sosBannerText:{fontWeight: '700', fontSize: 12, letterSpacing: 0.4, flex: 1},

  // SOS Actions
  sosActions:    {flexDirection: 'row', gap: 8, marginBottom: 10},
  sosBtn:        {flex: 2, backgroundColor: '#FF3366', borderRadius: 12, paddingVertical: 13, alignItems: 'center'},
  sosBtnText:    {color: '#fff', fontWeight: '800', fontSize: 14, letterSpacing: 0.3},
  dismissBtn:    {flex: 1, backgroundColor: '#111827', borderRadius: 12, paddingVertical: 13, alignItems: 'center', borderWidth: 1, borderColor: '#1E2D45'},
  dismissBtnText:{color: '#A0AEC0', fontWeight: '600', fontSize: 13},

  // Badges
  badgeRow:   {flexDirection: 'row', gap: 6, marginBottom: 10},
  badge:      {flexDirection: 'row', alignItems: 'center', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5, gap: 5, borderWidth: 1},
  badgeIcon:  {fontSize: 11},
  badgeDot:   {width: 5, height: 5, borderRadius: 2.5},
  badgeText:  {fontSize: 11, fontWeight: '600'},
  snapshotBadge: {
    alignSelf: 'flex-start',
    marginTop: -2,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFD1661A',
    borderColor: '#FFD16666',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  snapshotBadgeIcon: {fontSize: 12},
  snapshotBadgeText: {
    color: '#FFD166',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },

  // HR Hero
  hrHero:      {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#0C0F1A', borderRadius: 16, paddingVertical: 14, paddingHorizontal: 16, marginBottom: 10, borderWidth: 1, borderColor: '#111827'},
  hrHeroLeft:  {flex: 1},
  hrHeroLabel: {fontSize: 10, color: '#3D4E6A', letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 4},
  hrHeroValRow:{flexDirection: 'row', alignItems: 'flex-end', gap: 4},
  hrHeroVal:   {fontSize: 50, fontWeight: '900', color: '#E8EDF5', lineHeight: 54},
  hrHeroUnit:  {fontSize: 15, color: '#3D4E6A', fontWeight: '600', marginBottom: 6},
  hrHeroMeta:  {fontSize: 11, color: '#3D4E6A', marginTop: 3},
  hrSourceDot: {color: '#00E5A0'},
  hrHeroRight: {paddingLeft: 12},
  hrPulseRing: {width: 56, height: 56, borderRadius: 28, borderWidth: 2, alignItems: 'center', justifyContent: 'center'},
  hrPulseEmoji:{fontSize: 24},

  // Metric Grid
  grid:        {flexDirection: 'row', gap: 8, marginBottom: 10},
  metricCard:  {flex: 1, backgroundColor: '#0C0F1A', borderRadius: 14, padding: 12, borderWidth: 1, borderColor: '#111827', alignItems: 'center'},
  metricIconWrap:{width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 6},
  metricIcon:  {fontSize: 18},
  metricValue: {fontSize: 20, fontWeight: '800'},
  metricUnit:  {fontSize: 11, color: '#3D4E6A', fontWeight: '400'},
  metricLabel: {fontSize: 9, color: '#3D4E6A', marginTop: 2, textTransform: 'uppercase', letterSpacing: 1},
  metricSub:   {fontSize: 10, fontWeight: '600', marginTop: 3},

  // Section
  section:       {backgroundColor: '#0C0F1A', borderRadius: 16, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: '#111827'},
  sectionHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4},
  sectionTitle:  {fontSize: 13, fontWeight: '700', color: '#E8EDF5', letterSpacing: 0.3},
  sectionDesc:   {fontSize: 11, color: '#3D4E6A', marginBottom: 11, lineHeight: 17},
  connectedPill: {flexDirection: 'row', alignItems: 'center', backgroundColor: '#00E5A010', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 3, gap: 4, borderWidth: 1, borderColor: '#00E5A030'},
  connectedDot:  {width: 5, height: 5, borderRadius: 2.5, backgroundColor: '#00E5A0'},
  connectedText: {fontSize: 10, color: '#00E5A0', fontWeight: '600'},

  // Breakdown bars
  barRow:      {flexDirection: 'row', alignItems: 'center', marginBottom: 11, gap: 10},
  barIconWrap: {width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center'},
  barIcon:     {fontSize: 15},
  barContent:  {flex: 1},
  barTopRow:   {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 5},
  barLabel:    {fontSize: 12, color: '#E8EDF5', fontWeight: '600'},
  barTrack:    {height: 5, backgroundColor: '#1A2235', borderRadius: 3, overflow: 'hidden'},
  barFill:     {height: 5, borderRadius: 3},
  barScore:    {fontSize: 12, fontWeight: '800'},
  barMax:      {fontSize: 10, color: '#3D4E6A', fontWeight: '400'},
  barPct:      {fontSize: 9, marginTop: 4, letterSpacing: 0.3},
  scorePill:   {flexDirection: 'row', alignItems: 'center', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1},
  scorePillText:{fontSize: 11, fontWeight: '800'},

  // Buttons
  btnPrimary: {backgroundColor: '#1A3A8F', borderRadius: 12, paddingVertical: 12, alignItems: 'center', borderWidth: 1, borderColor: '#2D55CC'},
  btnDanger:  {backgroundColor: '#2A0815', borderRadius: 12, borderWidth: 1, borderColor: '#FF336650', paddingVertical: 12, alignItems: 'center'},
  btnMuted:   {opacity: 0.4},
  btnText:    {color: '#E8EDF5', fontWeight: '700', fontSize: 13, letterSpacing: 0.3},
  errorText:  {color: '#FF3366', fontSize: 11, marginBottom: 8, textAlign: 'center'},

  // BLE Panel — compact fixed strip above scroll
  blePanel:                   {marginHorizontal: 14, marginTop: 8, marginBottom: 4, backgroundColor: '#0C0F1A', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderColor: '#111827'},
  blePanelRow:                {flexDirection: 'row', alignItems: 'center', gap: 10},
  bleIconWrap:                {width: 44, height: 44, alignItems: 'center', justifyContent: 'center'},
  bleScanRing:                {position: 'absolute', width: 44, height: 44, borderRadius: 22, borderWidth: 1.5},
  bleIconCircle:              {width: 38, height: 38, borderRadius: 19, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center'},
  bleIconText:                {fontSize: 17},
  bleStatusDot:               {position: 'absolute', bottom: 1, right: 1, width: 10, height: 10, borderRadius: 5, borderWidth: 2, borderColor: '#0C0F1A'},
  bleInfo:                    {flex: 1},
  bleDeviceName:              {fontSize: 13, fontWeight: '700', color: '#E8EDF5', marginBottom: 1},
  bleDeviceSub:               {fontSize: 10, color: '#3D4E6A', letterSpacing: 0.2},
  bleHrRow:                   {flexDirection: 'row', alignItems: 'baseline', gap: 1},
  bleHrVal:                   {fontSize: 18, fontWeight: '900', color: '#00E5A0', lineHeight: 22},
  bleHrUnit:                  {fontSize: 11, color: '#3D4E6A', fontWeight: '600'},
  bleLiveBadge:               {flexDirection: 'row', alignItems: 'center', backgroundColor: '#00E5A012', borderRadius: 6, paddingHorizontal: 5, paddingVertical: 1, borderWidth: 1, borderColor: '#00E5A030', gap: 3, marginLeft: 5},
  bleLiveDot:                 {width: 4, height: 4, borderRadius: 2, backgroundColor: '#00E5A0'},
  bleLiveText:                {fontSize: 8, color: '#00E5A0', fontWeight: '800', letterSpacing: 1},
  scanDots:                   {flexDirection: 'row', alignItems: 'center', gap: 3},
  scanDot:                    {width: 5, height: 5, borderRadius: 2.5, backgroundColor: '#7EB8F7'},
  bleActionBtn:               {backgroundColor: '#122040', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 14, borderWidth: 1, borderColor: '#2D55CC', alignItems: 'center', justifyContent: 'center', minHeight: 34, minWidth: 56},
  bleActionBtnMuted:          {opacity: 0.55, borderColor: '#7EB8F740', paddingHorizontal: 8},
  bleActionBtnText:           {color: '#7EB8F7', fontWeight: '700', fontSize: 12, letterSpacing: 0.4},
  bleActionBtnDisconnect:     {backgroundColor: '#1A0A0F', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: '#FF336640', alignItems: 'center', justifyContent: 'center'},
  bleActionBtnDisconnectText: {color: '#FF3366', fontWeight: '700', fontSize: 11, letterSpacing: 0.3},
  bleErrorBox:                {flexDirection: 'row', alignItems: 'center', backgroundColor: '#FF336610', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: '#FF336630', marginTop: 8, gap: 6},
  bleErrorIcon:               {fontSize: 11, color: '#FF3366'},
  bleErrorText:               {flex: 1, color: '#FF3366', fontSize: 10, lineHeight: 15},

  // Tip
  tipCard: {flexDirection: 'row', backgroundColor: '#0C0F1A', borderRadius: 16, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: '#111827', gap: 12, alignItems: 'flex-start'},
  tipIcon: {fontSize: 20, marginTop: 2},
  tipBody: {flex: 1},
  tipTitle:{fontSize: 12, fontWeight: '700', color: '#E8EDF5', marginBottom: 4},
  tipText: {color: '#A0AEC0', fontSize: 12, lineHeight: 18},
});

export default styles;
